version: '3'

tasks:
  run:
    deps: [build]
    summary: Runs the backend server
    cmds:
      - ./couplet
  build:
    deps: [generate]
    summary: Build the backend executable
    sources:
      - ./**/*.go
    generates:
      - couplet
    cmds:
      - go mod download
      - go build -o couplet
  generate:
    aliases: [gen]
    summary: Generate server code from OpenAPI spec
    sources:
      - openapi.yaml
    generates:
      - api/**
    cmds:
      - go generate
  clean:
    summary: Delete build files
    cmds:
      - rm -f couplet
      - rm -rf api

  test:
    deps: [generate]
    summary: Run backend tests
    cmds:
      - go test
  check:
    deps: [generate]
    summary: Run static analysis checks
    cmds:
      - golangci-lint run
      - go mod tidy
      - go fmt
      - go vet